// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiO7CoWMhGM5beG8ocu-Kz0k0ArSqyVBk',
    appId: '1:317571619135:web:2ec710c5e224187212db8a',
    messagingSenderId: '317571619135',
    projectId: 'agrirent-4d70f',
    authDomain: 'agrirent-4d70f.firebaseapp.com',
    storageBucket: 'agrirent-4d70f.firebasestorage.app',
    measurementId: 'G-E34WH3PGDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAcyvSzZPRb9YKQQiVMVlhYfKWteOIle8',
    appId: '1:317571619135:android:6783d5de9ab08f0d12db8a',
    messagingSenderId: '317571619135',
    projectId: 'agrirent-4d70f',
    storageBucket: 'agrirent-4d70f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQVhKe6nX8d6U5X8FL-h00r1bghSi0ek8',
    appId: '1:317571619135:ios:3ba83acd77ef0d4912db8a',
    messagingSenderId: '317571619135',
    projectId: 'agrirent-4d70f',
    storageBucket: 'agrirent-4d70f.firebasestorage.app',
    iosBundleId: 'com.example.agriRent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQVhKe6nX8d6U5X8FL-h00r1bghSi0ek8',
    appId: '1:317571619135:ios:3ba83acd77ef0d4912db8a',
    messagingSenderId: '317571619135',
    projectId: 'agrirent-4d70f',
    storageBucket: 'agrirent-4d70f.firebasestorage.app',
    iosBundleId: 'com.example.agriRent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiO7CoWMhGM5beG8ocu-Kz0k0ArSqyVBk',
    appId: '1:317571619135:web:63006267187fbd6212db8a',
    messagingSenderId: '317571619135',
    projectId: 'agrirent-4d70f',
    authDomain: 'agrirent-4d70f.firebaseapp.com',
    storageBucket: 'agrirent-4d70f.firebasestorage.app',
    measurementId: 'G-254YDFPLB8',
  );
}
